import orderBy from 'lodash/orderBy';

const createPath = fileName => `https://peterneely.github.io/icons/${fileName}`;

const links = [
  { name: '1Password', link: 'http://neelys.1password.com/', icon: createPath('1password.png') },
  { name: 'AT&T', link: 'http://www.att.com/', icon: createPath('att.png') },
  { name: 'Aetna', link: 'https://health.aetna.com/', icon: createPath('aetna.png') },
  { name: 'Ally', link: 'http://secure.ally.com/#/dashboard', icon: createPath('ally.jpg') },
  { name: 'AlternativeTo', link: 'http://alternativeto.net/', icon: createPath('alternativeto.png') },
  { name: 'Amazon', link: 'http://amazon.com/', icon: createPath('amazon.png') },
  { name: 'American Express', link: 'http://www.americanexpress.com/', icon: createPath('amex.png') },
  { name: 'Apple Developer Forums', link: 'http://forums.developer.apple.com/welcome', icon: createPath('xcode.png') },
  { name: 'Apple', link: 'http://www.apple.com/', icon: createPath('apple.png') },
  { name: 'Bank of America', link: 'http://www.bankofamerica.com/', icon: createPath('bofa.png') },
  { name: 'Best Parking', link: 'http://losangeles.bestparking.com/', icon: createPath('bestparking.png') },
  { name: 'Bitbucket', link: 'http://bitbucket.org/dashboard/overview', icon: createPath('bitbucket.png') },
  { name: 'CanIUse', link: 'http://caniuse.com/', icon: createPath('caniuse.png') },
  { name: 'Chase', link: 'http://cards.chase.com/cc/Account/Activity/561745339', icon: createPath('chase.png') },
  { name: 'Cigna', link: 'http://my.cigna.com/web/secure/my/coverage/dental', icon: createPath('cigna.png') },
  { name: 'Code School', link: 'http://www.codeschool.com/', icon: createPath('codeschool.jpg') },
  { name: 'CodeSandbox', link: 'http://codesandbox.io/s/vanilla', icon: createPath('codesandbox.png') },
  { name: 'Craigslist', link: 'http://losangeles.craigslist.org/search/cta?sort=date&max_price=2500&auto_title_status=1&auto_bodytype=8&query=torrance', icon: createPath('craigslist.png') },
  { name: 'Credit Karma', link: 'http://www.creditkarma.com/dashboard', icon: createPath('creditkarma.png') },
  { name: 'Dropbox', link: 'http://www.dropbox.com/home', icon: createPath('dropbox.jpg') },
  { name: 'ES6', link: 'http://kangax.github.io/compat-table/es6/', icon: createPath('es6.png') },
  { name: 'Egghead', link: 'http://egghead.io/', icon: createPath('egghead.jpg') },
  { name: 'Experian ID Notify', link: 'http://services.idnotify.com/dashboard', icon: createPath('idnotify.png') },
  { name: 'Facebook', link: 'http://www.facebook.com/login.php', icon: createPath('fb.png') },
  { name: 'Fast', link: 'http://fast.com/', icon: createPath('fast.png') },
  { name: 'Feedly', link: 'http://feedly.com/', icon: createPath('feedly.png') },
  { name: 'Firebase', link: 'http://console.firebase.google.com/u/0/', icon: createPath('firebase.png') },
  { name: 'FlightAware', link: 'http://flightaware.com/', icon: createPath('flightaware.png') },
  { name: 'Geico', link: 'http://ecams.geico.com/ecams/login.xhtml?msgid=MSG150_8', icon: createPath('geico.jpeg') },
  { name: 'Giphy', link: 'http://giphy.com/', icon: createPath('giphy.png') },
  { name: 'GitHub Peter', link: 'http://github.com/peterneely?tab=repositories', icon: createPath('github-peter.png') },
  { name: 'GitHub Sony', link: 'http://github.sie.sony.com/SIE-Private/SCP', icon: createPath('github-sony.png') },
  { name: 'Google Flights', link: 'http://www.google.com/flights/', icon: createPath('flights.png') },
  { name: 'Google One', link: 'http://one.google.com/', icon: createPath('googleOne.jpg') },
  { name: 'Google Translate', link: 'http://translate.google.com/', icon: createPath('translate.png') },
  { name: 'Gravatar', link: 'http://en.gravatar.com/', icon: createPath('gravatar.jpg') },
  { name: 'HTML5 Please', link: 'http://html5please.com/', icon: createPath('html5please.jpg') },
  { name: 'Harvest', link: 'http://pneely.harvestapp.com/time', icon: createPath('harvest.png') },
  { name: 'Heroku', link: 'http://dashboard.heroku.com/apps', icon: createPath('heroku.png') },
  { name: 'Homebridge', link: 'http://financingaccountconnect.com/Homebridge/LoanService/accounts/accountDetail/0', icon: createPath('homebridge.jpg') },
  { name: 'Hulu', link: 'http://www.hulu.com/', icon: createPath('hulu.jpg') },
  { name: 'IMDB', link: 'http://www.imdb.com/', icon: createPath('imdb.png') },
  { name: 'JWT', link: 'http://jwt.io/', icon: createPath('jwt.svg') },
  { name: 'Jen Simmons Labs', link: 'http://labs.jensimmons.com/', icon: createPath('jenlabs.png') },
  { name: 'JustWatch', link: 'http://www.justwatch.com/us/provider/netflix', icon: createPath('justwatch.png') },
  { name: 'Kaiser Permanente', link: 'http://healthy.kaiserpermanente.org/health/mycare/consumer/my-health-manager', icon: createPath('kaiser.png') },
  { name: 'King\'s Harbor', link: 'http://kingsharbor.org/', icon: createPath('khc.jpg') },
  { name: 'LA Fitness', link: 'http://www.lafitness.com/Pages/billinghistory.aspx?scr=receipts', icon: createPath('lafitness.png') },
  { name: 'LinkedIn', link: 'http://www.linkedin.com/in/pgneely', icon: createPath('linkedin.jpg') },
  { name: 'Lloyds Bank', link: 'http://online.lloydsbank.co.uk/personal/logon/login.jsp', icon: createPath('lloyds.jpg') },
  { name: 'Logix', link: 'http://olb.logixbanking.com/User/MainAccounts/List', icon: createPath('logix.png') },
  { name: 'Meetup', link: 'http://www.meetup.com/find/', icon: createPath('meetup.png') },
  { name: 'Microsoft', link: 'http://stores.office.com/myaccount/home.aspx?ui=en-US&rs=en-GB&ad=GB&s=1&auth=0&fromAR=3', icon: createPath('microsoft.png') },
  { name: 'Mint', link: 'http://wwws.mint.com/overview.event', icon: createPath('mint.png') },
  { name: 'MongoDB', link: 'http://cloud.mongodb.com/v2/5b29a4710bd66b2c58f13b28#clusters?tooltip=nds.security&step=0', icon: createPath('mongodb-atlas.png') },
  { name: 'MyCarFax', link: 'http://www.mycarfax.com/', icon: createPath('mycarfax.png') },
  { name: 'Netflix DVD', link: 'http://dvd.netflix.com/MemberHome', icon: createPath('netflixdvd.jpg') },
  { name: 'Netflix', link: 'http://www.netflix.com/', icon: createPath('netflix.png') },
  { name: 'Node Compatibility', link: 'http://node.green/', icon: createPath('nodegreen.png') },
  { name: 'Our Groceries', link: 'http://www.ourgroceries.com/your-lists/list/IkFiAxpB0g3JdigiZj_U3q', icon: createPath('ourgroceries.png') },
  { name: 'Parallels Access', link: 'http://access.parallels.com/#/computers/', icon: createPath('parallels.jpg') },
  { name: 'ParkMe', link: 'http://www.parkme.com/los-angeles-parking', icon: createPath('parkme.png') },
  { name: 'PayPal', link: 'http://www.paypal.com/myaccount/home', icon: createPath('paypal.png') },
  { name: 'PlaneFinder', link: 'http://planefinder.net/', icon: createPath('planefinder.png') },
  { name: 'Plunkr', link: 'http://plnkr.co/edit/?p=catalogue', icon: createPath('plunkr.png') },
  { name: 'Pluralsight', link: 'http://www.pluralsight.com/', icon: createPath('pluralsight.png') },
  { name: 'Portainer', link: 'http://localhost:9000/#/containers/', icon: createPath('portainer.png') },
  { name: 'PowerSchool', link: 'http://torrance.powerschool.com/guardian/home.html', icon: createPath('powerschool.png') },
  { name: 'Providence', link: 'http://mychartor.providence.org/mychart/', icon: createPath('providence.png') },
  { name: 'Ray Wenderlich', link: 'http://www.raywenderlich.com/', icon: createPath('raywenderlich.png') },
  { name: 'React Style Guide: AirBnB', link: 'http://github.com/airbnb/javascript/tree/master/react#naming', icon: createPath('react.png') },
  { name: 'Regex 101', link: 'http://regex101.com/', icon: createPath('regex101.jpg') },
  { name: 'Regexr', link: 'http://www.regexr.com/', icon: createPath('regexr.png') },
  { name: 'Repl-it', link: 'http://repl.it/languages/javascript', icon: createPath('replit.png') },
  { name: 'SCE', link: 'http://www.sce.com/wps/myportal/home/mysce/myaccount', icon: createPath('sce.jpg') },
  { name: 'SVG Editor', link: 'http://petercollingridge.appspot.com/svg-editor', icon: createPath('svg.png') },
  { name: 'Seat Guru', link: 'http://www.seatguru.com/', icon: createPath('seatguru.jpg') },
  { name: 'Shazam', link: 'http://www.shazam.com/myshazam', icon: createPath('shazam.png') },
  { name: 'SoCalGas', link: 'http://myaccount.socalgas.com/myAccount/newscg.portal', icon: createPath('socalgas.jpg') },
  { name: 'Spectrum', link: 'http://www.spectrum.net/login/', icon: createPath('spectrum.png') },
  { name: 'Stackblitz', link: 'http://stackblitz.com/', icon: createPath('stackblitz.png') },
  { name: 'Synchrony', link: 'http://consumercenter.mysynchrony.com/consumercenter/homeaction.do?strutsToken=tokenValue&tokenValue=90YB-29G9-Z06G-JIJV-3QGD-W61K-5L9D-648B-EMZQ-01IQ', icon: createPath('synchrony.png') },
  { name: 'Team Treehouse', link: 'http://teamtreehouse.com/library', icon: createPath('treehouse.png') },
  { name: 'Thinkster', link: 'http://thinkster.io/', icon: createPath('thinkster.png') },
  { name: 'Trello', link: 'http://trello.com/', icon: createPath('trello.png') },
  { name: 'TurboTax', link: 'http://myturbotax.intuit.com/inprogress/', icon: createPath('turbotax.jpg') },
  { name: 'TutsPlus', link: 'http://tutsplus.com/account/courses', icon: createPath('tuts.png') },
  { name: 'Uber', link: 'http://riders.uber.com/trips', icon: createPath('uber.jpg') },
  { name: 'Udemy', link: 'http://www.udemy.com/courses/', icon: createPath('udemy.svg') },
  { name: 'VSP', link: 'http://www.vsp.com/benefits-detail.html', icon: createPath('vsp.JPG') },
  { name: 'Venmo', link: 'http://venmo.com/peterneely', icon: createPath('venmo.png') },
  { name: 'W3 Schools', link: 'https://www.w3schools.com/colors/colors_mixer.asp', icon: createPath('colors.gif') },
  { name: 'Yelp', link: 'http://www.yelp.com/torrance-ca-us', icon: createPath('yelp.jpeg') },
  { name: 'YouTube', link: 'http://www.youtube.com/', icon: createPath('youtube.svg') },
  { name: 'eBay', link: 'http://www.ebay.com/', icon: createPath('ebay.jpg') },
  { name: 'px to em', link: 'http://pxtoem.com/', icon: createPath('pxtoem.png') },
];

const sortedLinks = orderBy(links, ({ name = '' }) => name.toLowerCase());

export { sortedLinks as staticLinks };
