export const BOOKMARKS_LOAD_BOOKMARKS_ERROR = 'BOOKMARKS_LOAD_BOOKMARKS_ERROR';
export const BOOKMARKS_LOAD_BOOKMARKS_SUCCESS = 'BOOKMARKS_LOAD_BOOKMARKS_SUCCESS';
export const BOOKMARKS_LOAD_FOLDERS_ERROR = 'BOOKMARKS_LOAD_FOLDERS_ERROR';
export const BOOKMARKS_LOAD_FOLDERS_SUCCESS = 'BOOKMARKS_LOAD_FOLDERS_SUCCESS';
export const BOOKMARKS_SET_FOLDER = 'BOOKMARKS_SET_FOLDER';
