import orderBy from 'lodash/orderBy';

const getIcon = fileName => `https://peterneely.github.io/icons/${fileName}`

const links = [
  { name: '1Password', link: 'http://neelys.1password.com/', icon: getIcon('1password.png') },
  { name: 'AT&T', link: 'http://www.att.com/', icon: getIcon('att.png') },
  { name: 'Aetna', link: 'https://health.aetna.com', icon: getIcon('aetna.png') },
  { name: 'Ally', link: 'http://secure.ally.com/#/dashboard', icon: getIcon('ally.jpg') },
  { name: 'AlternativeTo', link: 'http://alternativeto.net/', icon: getIcon('alternativeto.png') },
  { name: 'Amazon', link: 'http://amazon.com/', icon: getIcon('amazon.png') },
  { name: 'American Express', link: 'http://www.americanexpress.com/', icon: getIcon('amex.png') },
  { name: 'Apple Developer Forums', link: 'http://forums.developer.apple.com/welcome', icon: getIcon('xcode.png') },
  { name: 'Apple', link: 'http://www.apple.com/', icon: getIcon('apple.png') },
  { name: 'Bank of America', link: 'http://www.bankofamerica.com/', icon: getIcon('bofa.png') },
  { name: 'Best Parking', link: 'http://losangeles.bestparking.com/', icon: getIcon('bestparking.png') },
  { name: 'Bitbucket', link: 'http://bitbucket.org/dashboard/overview', icon: getIcon('bitbucket.png') },
  { name: 'CanIUse', link: 'http://caniuse.com/', icon: getIcon('caniuse.png') },
  { name: 'Chase', link: 'http://cards.chase.com/cc/Account/Activity/561745339', icon: getIcon('chase.png') },
  { name: 'Cigna', link: 'http://my.cigna.com/web/secure/my/coverage/dental', icon: getIcon('cigna.png') },
  { name: 'Code School', link: 'http://www.codeschool.com/', icon: getIcon('codeschool.jpg') },
  { name: 'CodeSandbox', link: 'http://codesandbox.io/s/vanilla', icon: getIcon('codesandbox.png') },
  { name: 'Craigslist', link: 'http://losangeles.craigslist.org/search/cta?sort=date&max_price=2500&auto_title_status=1&auto_bodytype=8&query=torrance', icon: getIcon('craigslist.png') },
  { name: 'Credit Karma', link: 'http://www.creditkarma.com/dashboard', icon: getIcon('creditkarma.png') },
  { name: 'Dropbox', link: 'http://www.dropbox.com/home', icon: getIcon('dropbox.jpg') },
  { name: 'ES6', link: 'http://kangax.github.io/compat-table/es6/', icon: getIcon('es6.png') },
  { name: 'Egghead', link: 'http://egghead.io/', icon: getIcon('egghead.jpg') },
  { name: 'Experian ID Notify', link: 'http://services.idnotify.com/dashboard', icon: getIcon('idnotify.png') },
  { name: 'Facebook', link: 'http://www.facebook.com/login.php', icon: getIcon('fb.png') },
  { name: 'Fast', link: 'http://fast.com/', icon: getIcon('fast.png') },
  { name: 'Feedly', link: 'http://feedly.com/', icon: getIcon('feedly.png') },
  { name: 'Firebase', link: 'http://console.firebase.google.com/u/0/', icon: getIcon('firebase.png') },
  { name: 'FlightAware', link: 'http://flightaware.com/', icon: getIcon('flightaware.png') },
  { name: 'Geico', link: 'http://ecams.geico.com/ecams/login.xhtml?msgid=MSG150_8', icon: getIcon('geico.jpeg') },
  { name: 'Giphy', link: 'http://giphy.com/', icon: getIcon('giphy.png') },
  { name: 'GitHub Peter', link: 'http://github.com/peterneely?tab=repositories', icon: getIcon('github-peter.png') },
  { name: 'GitHub Sony', link: 'http://github.sie.sony.com/SIE-Private/SCP', icon: getIcon('github-sony.png') },
  { name: 'Google Flights', link: 'http://www.google.com/flights/', icon: getIcon('flights.png') },
  { name: 'Google One', link: 'http://one.google.com/', icon: getIcon('googleOne.jpg') },
  { name: 'Google Translate', link: 'http://translate.google.com/', icon: getIcon('translate.png') },
  { name: 'Gravatar', link: 'http://en.gravatar.com/', icon: getIcon('gravatar.jpg') },
  { name: 'HTML5 Please', link: 'http://html5please.com/', icon: getIcon('html5please.jpg') },
  { name: 'Harvest', link: 'http://pneely.harvestapp.com/time', icon: getIcon('harvest.png') },
  { name: 'Heroku', link: 'http://dashboard.heroku.com/apps', icon: getIcon('heroku.png') },
  { name: 'Homebridge', link: 'http://financingaccountconnect.com/Homebridge/LoanService/accounts/accountDetail/0', icon: getIcon('homebridge.jpg') },
  { name: 'Hulu', link: 'http://www.hulu.com/', icon: getIcon('hulu.jpg') },
  { name: 'IMDB', link: 'http://www.imdb.com/', icon: getIcon('imdb.png') },
  { name: 'JWT', link: 'http://jwt.io/', icon: getIcon('jwt.svg') },
  { name: 'Jen Simmons Labs', link: 'http://labs.jensimmons.com/', icon: getIcon('jenlabs.png') },
  { name: 'JustWatch', link: 'http://www.justwatch.com/us/provider/netflix', icon: getIcon('justwatch.png') },
  { name: 'Kaiser Permanente', link: 'http://healthy.kaiserpermanente.org/health/mycare/consumer/my-health-manager', icon: getIcon('kaiser.png') },
  { name: 'King\'s Harbor', link: 'http://kingsharbor.org/', icon: getIcon('khc.jpg') },
  { name: 'LA Fitness', link: 'http://www.lafitness.com/Pages/billinghistory.aspx?scr=receipts', icon: getIcon('lafitness.png') },
  { name: 'LinkedIn', link: 'http://www.linkedin.com/in/pgneely', icon: getIcon('linkedin.jpg') },
  { name: 'Lloyds Bank', link: 'http://online.lloydsbank.co.uk/personal/logon/login.jsp', icon: getIcon('lloyds.jpg') },
  { name: 'Logix', link: 'http://olb.logixbanking.com/User/MainAccounts/List', icon: getIcon('logix.png') },
  { name: 'Meetup', link: 'http://www.meetup.com/find/', icon: getIcon('meetup.png') },
  { name: 'Microsoft', link: 'http://stores.office.com/myaccount/home.aspx?ui=en-US&rs=en-GB&ad=GB&s=1&auth=0&fromAR=3', icon: getIcon('microsoft.png') },
  { name: 'Mint', link: 'http://wwws.mint.com/overview.event', icon: getIcon('mint.png') },
  { name: 'MongoDB', link: 'http://cloud.mongodb.com/v2/5b29a4710bd66b2c58f13b28#clusters?tooltip=nds.security&step=0', icon: getIcon('mongodb-atlas.png') },
  { name: 'MyCarFax', link: 'http://www.mycarfax.com/', icon: getIcon('mycarfax.png') },
  { name: 'Netflix DVD', link: 'http://dvd.netflix.com/MemberHome', icon: getIcon('netflixdvd.jpg') },
  { name: 'Netflix', link: 'http://www.netflix.com/', icon: getIcon('netflix.png') },
  { name: 'Node Compatibility', link: 'http://node.green/', icon: getIcon('nodegreen.png') },
  { name: 'Our Groceries', link: 'http://www.ourgroceries.com/your-lists/list/IkFiAxpB0g3JdigiZj_U3q', icon: getIcon('ourgroceries.png') },
  { name: 'Parallels Access', link: 'http://access.parallels.com/#/computers/', icon: getIcon('parallels.jpg') },
  { name: 'ParkMe', link: 'http://www.parkme.com/los-angeles-parking', icon: getIcon('parkme.png') },
  { name: 'PayPal', link: 'http://www.paypal.com/myaccount/home', icon: getIcon('paypal.png') },
  { name: 'PlaneFinder', link: 'http://planefinder.net/', icon: getIcon('planefinder.png') },
  { name: 'Plunkr', link: 'http://plnkr.co/edit/?p=catalogue', icon: getIcon('plunkr.png') },
  { name: 'Pluralsight', link: 'http://www.pluralsight.com/', icon: getIcon('pluralsight.png') },
  { name: 'Portainer', link: 'http://localhost:9000/#/containers/', icon: getIcon('portainer.png') },
  { name: 'PowerSchool', link: 'http://torrance.powerschool.com/guardian/home.html', icon: getIcon('powerschool.png') },
  { name: 'Providence', link: 'http://mychartor.providence.org/mychart/', icon: getIcon('providence.png') },
  { name: 'Ray Wenderlich', link: 'http://www.raywenderlich.com/', icon: getIcon('raywenderlich.png') },
  { name: 'React Style Guide: AirBnB', link: 'http://github.com/airbnb/javascript/tree/master/react#naming', icon: getIcon('react.png') },
  { name: 'Regex 101', link: 'http://regex101.com/', icon: getIcon('regex101.jpg') },
  { name: 'Regexr', link: 'http://www.regexr.com/', icon: getIcon('regexr.png') },
  { name: 'Repl-it', link: 'http://repl.it/languages/javascript', icon: getIcon('replit.png') },
  { name: 'SCE', link: 'http://www.sce.com/wps/myportal/home/mysce/myaccount', icon: getIcon('sce.jpg') },
  { name: 'SVG Editor', link: 'http://petercollingridge.appspot.com/svg-editor', icon: getIcon('svg.png') },
  { name: 'Seat Guru', link: 'http://www.seatguru.com/', icon: getIcon('seatguru.jpg') },
  { name: 'Shazam', link: 'http://www.shazam.com/myshazam', icon: getIcon('shazam.png') },
  { name: 'SoCalGas', link: 'http://myaccount.socalgas.com/myAccount/newscg.portal', icon: getIcon('socalgas.jpg') },
  { name: 'Spectrum', link: 'http://www.spectrum.net/login/', icon: getIcon('spectrum.png') },
  { name: 'Stackblitz', link: 'http://stackblitz.com/', icon: getIcon('stackblitz.png') },
  { name: 'Synchrony', link: 'http://consumercenter.mysynchrony.com/consumercenter/homeaction.do?strutsToken=tokenValue&tokenValue=90YB-29G9-Z06G-JIJV-3QGD-W61K-5L9D-648B-EMZQ-01IQ', icon: getIcon('synchrony.png') },
  { name: 'Team Treehouse', link: 'http://teamtreehouse.com/library', icon: getIcon('treehouse.png') },
  { name: 'Thinkster', link: 'http://thinkster.io/', icon: getIcon('thinkster.png') },
  { name: 'Trello', link: 'http://trello.com/', icon: getIcon('trello.png') },
  { name: 'TurboTax', link: 'http://myturbotax.intuit.com/inprogress/', icon: getIcon('turbotax.jpg') },
  { name: 'TutsPlus', link: 'http://tutsplus.com/account/courses', icon: getIcon('tuts.png') },
  { name: 'Uber', link: 'http://riders.uber.com/trips', icon: getIcon('uber.jpg') },
  { name: 'Udemy', link: 'http://www.udemy.com/courses/', icon: getIcon('udemy.svg') },
  { name: 'VSP', link: 'http://www.vsp.com/benefits-detail.html', icon: getIcon('vsp.JPG') },
  { name: 'Venmo', link: 'http://venmo.com/peterneely', icon: getIcon('venmo.png') },
  { name: 'W3 Schools', link: 'https://www.w3schools.com/colors/colors_mixer.asp', icon: getIcon('colors.gif') },
  { name: 'Yelp', link: 'http://www.yelp.com/torrance-ca-us', icon: getIcon('yelp.jpeg') },
  { name: 'YouTube', link: 'http://www.youtube.com/', icon: getIcon('youtube.svg') },
  { name: 'eBay', link: 'http://www.ebay.com/', icon: getIcon('ebay.jpg') },
  { name: 'px to em', link: 'http://pxtoem.com/', icon: getIcon('pxtoem.png') },
];

const sortedLinks = orderBy(links, ({ name = '' }) => name.toLowerCase());

export { sortedLinks as links };
