export const SETTINGS_LOAD_SETTINGS_ERROR = 'SETTINGS_LOAD_SETTINGS_ERROR';
export const SETTINGS_LOAD_SETTINGS_SUCCESS = 'SETTINGS_LOAD_SETTINGS_SUCCESS';
export const SETTINGS_SAVE_SETTINGS_ERROR = 'SETTINGS_SAVE_SETTINGS_ERROR';
export const SETTINGS_SAVE_SETTINGS_SUCCESS = 'SETTINGS_SAVE_SETTINGS_SUCCESS';
export const SETTINGS_TOGGLE_SETTINGS = 'SETTINGS_TOGGLE_SETTINGS';
