export const APP_LOAD_TILES_ERROR = 'APP_LOAD_TILES_ERROR';
export const APP_LOAD_TILES_SUCCESS = 'APP_LOAD_TILES_SUCCESS';
export const APP_SAVE_SETTINGS_ERROR = 'APP_SAVE_SETTINGS_ERROR';
export const APP_SAVE_SETTINGS_SUCCESS = 'APP_SAVE_SETTINGS_SUCCESS';
export const APP_TOGGLE_SETTINGS = 'APP_TOGGLE_SETTINGS';
