export const APP_LOAD_TILES_ERROR = 'APP_LOAD_TILES_ERROR';
export const APP_LOAD_TILES_SUCCESS = 'APP_LOAD_TILES_SUCCESS';
export const APP_SET_APP_READY = 'APP_SET_APP_READY';
export const APP_SET_FOLDER = 'APP_SET_FOLDER';
